## 直线检测算法汇总

在一些任务场景中，通常会用到直线检测算法，比如车道线检测、长度测量等。


### Hough_line 直线检测

Hough变换常用于直线检测、圆检测、椭圆检测等。实现步骤如下：

- 创建二维数组或累加器，并将其初始值设置为零
- 用$r$表示行，用$\theta$表示列
- 数组的大小取决于所需要的精度。假设希望角度的精度为1度，则需要180列
- 对于$r$，可能的最大距离是图像的对角线长度。因此取一个像素精度，行数可以是图像的对角线长度

In [6]:
# coding=utf-8
# 导入相应的python包
import cv2 
import numpy as np 
import os
  
# 读取输入图片
img = cv2.imread('../image/lineDetection/line_detection.png') 
# 将彩色图片灰度化
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) 
# 使用Canny边缘检测 
edges = cv2.Canny(gray,50,200,apertureSize = 3) 
# 进行Hough_line直线检测
lines = cv2.HoughLines(edges,1,np.pi/10, 200) 
print(lines)
# 遍历每一个r和theta
for i in range(len(lines)):
    r,theta = lines[i, 0, 0], lines[i, 0, 1]
    # 存储cos(theta)的值
    a = np.cos(theta)
    # 存储sin(theta)的值
    b = np.sin(theta) 
    # 存储rcos(theta)的值
    x0 = a*r 
    # 存储rsin(theta)的值 
    y0 = b*r  
    # 存储(rcos(theta)-1000sin(theta))的值
    x1 = int(x0 + 1000*(-b)) 
    # 存储(rsin(theta)+1000cos(theta))的值
    y1 = int(y0 + 1000*(a)) 
    # 存储(rcos(theta)+1000sin(theta))的值
    x2 = int(x0 - 1000*(-b)) 
    # 存储(rsin(theta)-1000cos(theta))的值
    y2 = int(y0 - 1000*(a))  
    # 绘制直线结果  
    cv2.line(img,(x1,y1), (x2,y2), (0,255,0),2) 
# 保存结果
# cv2.imwrite('test3_r.jpg', img) 
cv2.imshow("result", img)
cv2.waitKey(0)


[[[728.   0.]]

 [[730.   0.]]

 [[395.   0.]]

 [[721.   0.]]

 [[393.   0.]]

 [[399.   0.]]

 [[719.   0.]]

 [[550.   0.]]

 [[613.   0.]]

 [[615.   0.]]

 [[638.   0.]]

 [[640.   0.]]

 [[449.   0.]]

 [[451.   0.]]

 [[512.   0.]]

 [[514.   0.]]

 [[575.   0.]]

 [[577.   0.]]

 [[676.   0.]]

 [[678.   0.]]

 [[703.   0.]]

 [[539.   0.]]

 [[552.   0.]]

 [[701.   0.]]

 [[474.   0.]]

 [[476.   0.]]

 [[413.   0.]]

 [[487.   0.]]

 [[489.   0.]]

 [[537.   0.]]

 [[411.   0.]]

 [[716.   0.]]

 [[426.   0.]]

 [[602.   0.]]

 [[424.   0.]]

 [[600.   0.]]

 [[651.   0.]]

 [[653.   0.]]

 [[588.   0.]]

 [[665.   0.]]

 [[663.   0.]]

 [[462.   0.]]

 [[590.   0.]]

 [[525.   0.]]

 [[527.   0.]]

 [[438.   0.]]

 [[436.   0.]]

 [[464.   0.]]

 [[501.   0.]]

 [[363.   0.]]

 [[564.   0.]]

 [[499.   0.]]

 [[562.   0.]]

 [[401.   0.]]

 [[714.   0.]]

 [[ 39.   0.]]

 [[132.   0.]]

 [[145.   0.]]

 [[143.   0.]]

 [[256.   0.]]

 [[361.   0.]]

 [[258.   0.]]

 [[294. 

-1